language: node_js
node_js:
  - 'node'
cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: 'wpocanvas'

script:
  - npm install  serverless-webpack
  - npm install -g serverless
  - npm install
  - npm run test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

deploy:
  provider: script
  script:
    - npm run deploy
  skip_cleanup: true
  on:
    repo: WPOCanvas/Audit-Tool-Backend
    branches:
      only:
        - master
