jobs:
  build:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i serverless-webpack
            sudo npm i -g serverless
            npm install

      - run: npm run test

  deploy:
    docker:
      - image: circleci/node:12.13
    steps:
      - checkout
      - run:
          name: Deploy Code to AWS
          command:
            - run: npm run deploy

  sonar:
    docker:
      - image: 'node:latest'
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  
version: 2.1
workflows:
  main:
    jobs:
      - sonar:
          context: SonarCloud
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master