version: 2
jobs:
  build:
    docker:
    - image: circleci/node:12.13

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i serverless-webpack
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - sonarcloud/scan
      - run: npm run test

  deploy:
    docker:
      - image: circleci/node:12.13

    steps:
      - run:
          name: Deploy Code to AWS
          command: 
            - run : npm run deploy

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        context: SONAR

      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

  

