version: 2
jobs: 
  build: 
    docker: 
      - image: "circleci/node:12.13"
    steps: 
      - checkout
      - restore_cache: 
          keys: 
            - "v1-dependencies-{{ checksum \"package.json\" }}"
            - v1-dependencies-
      - run: 
          command: |
              sudo npm i serverless-webpack
              sudo npm i -g serverless
              npm install
          name: "Install Serverless CLI and dependencies"
      - 
        save_cache: 
          key: "v1-dependencies-{{ checksum \"package.json\" }}"
          paths: 
            - node_modules
      - run: "npm run test"
      - sonarcloud/scan
  deploy: 
    docker: 
      - image: "circleci/node:12.13"
    steps: 
      - run: 
          command: 
            - run: "npm run deploy"
          name: "Deploy Code to AWS"

orbs: 
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows: 
  build-and-deploy: 
    jobs: 
      - build:
          context: SonarCloud
      - deploy: 
          filters: 
            branches: 
              only: master
          requires: 
            - build
